/**
 * LSWBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferTeacher } from './offerTeacher';
import { StudentOffer } from './studentOffer';
import { ClassOffer } from './classOffer';
import { OfferDate } from './offerDate';
import { Teacher } from './teacher';


export interface Offer { 
    offerId?: number;
    title?: string | null;
    description?: string | null;
    minStudents?: number;
    maxStudents?: number;
    meetingPoint?: string | null;
    costs?: number;
    location?: string | null;
    visibleForStudents?: number;
    teacherId?: number | null;
    teacher?: Teacher;
    offerDates?: Array<OfferDate> | null;
    offerTeachers?: Array<OfferTeacher> | null;
    studentOffers?: Array<StudentOffer> | null;
    classOffers?: Array<ClassOffer> | null;
}

