/**
 * LSWBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WaitingList } from './waitingList';
import { StudentOffer } from './studentOffer';
import { Clazz } from './clazz';


export interface Student { 
    studentId?: number;
    username?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    clazzId?: number;
    clazz?: Clazz;
    studentOffers?: Array<StudentOffer> | null;
    waitingLists?: Array<WaitingList> | null;
}

