/**
 * LSWBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferTeacher } from './offerTeacher';
import { Offer } from './offer';
import { Report } from './report';
import { TeacherLesson } from './teacherLesson';


export interface Teacher { 
    teacherId?: number;
    username?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    isAdmin?: number;
    offers?: Array<Offer> | null;
    reports?: Array<Report> | null;
    offerTeachers?: Array<OfferTeacher> | null;
    teachersLessons?: Array<TeacherLesson> | null;
}

