env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: '*.html'
    extends:
      - plugin:@angular-eslint/template/recommended
  - files: '*.ts'
    rules:
      indent:
        - error
        - 2
      linebreak-style:
        - error
        - windows
      quotes:
        - 2
        - single
      eqeqeq: 2
      comma-dangle:
        - 2
        - arrays: only-multiline
          objects: only-multiline
          functions: only-multiline
      no-console: 0
      no-debugger: 1
      no-extra-semi: 1
      no-extra-parens: 1
      no-irregular-whitespace: 0
      no-undef: 2
      no-unused-vars: 0
      semi: 1
      semi-spacing: 1
      valid-jsdoc:
        - 2
        - requireReturn: false
      "@angular-eslint/no-input-rename": 0
      "@angular-eslint/no-output-rename": 0
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - '@angular-eslint'
